---
title: "Untitled"
author: "Yuxin Yang"
date: "2023/2/13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read_excel("apm466/apm466 a1 data.xlsx")
View(df)

coupon <- as.numeric(df$Coupon)
maturity_date <- df$Maturity_Date
bond_name <- df$Bond_Name
clean_price_date <- c('2023-01-16','2023-01-17','2023-01-18','2023-01-19','2023-01-20'
                ,'2023-01-23','2023-01-24','2023-01-25','2023-01-26','2023-01-27')
clean_price_matrix <- matrix(c(df$'2023_1_16',df$"2023_1_17",df$"2023_1_18",df$"2023_1_19",df$"2023_1_20",df$"2023_1_23",
                         df$"2023_1_24",df$"2023_1_25",df$"2023_1_26",df$"2023_1_27"), nrow=10, ncol=10,byrow=TRUE)


# YTM 

## Calculate YTM
matrix_ytm <- matrix("numeric", nrow=10, ncol=10)
for (j in c(1:10)){
  for (i in c(1:10)){
    matrix_ytm[i,j]= bond.yield(settle=clean_price_date[i],mature=maturity_date[j],coupon=coupon[j],
                                freq=2,clean_price_matrix[,j][i], comp.freq=2,redemption_value = 100)
  }
}

matrix_ytm[1,]

## Plot of Yield to Maturity
date <- c(16,17,18,19,20,23,24,25,26,27)
color <- c("blue","orange","green","purple","pink","gray","yellow","dark blue","red")
plot(date, matrix_ytm[1,],type="o", xlab="Date", ylab="YTM",ylim=c(0.026,0.031))
for (i in c(2:10)){
  lines(date, matrix_ytm[i,],type="o",col=color[i-1])
}

legend("bottomright", legend=bond_name,pch=c(20,20),col=color,lty=1,cex=0.3)

#Spot Rate

## Dirty Price

dirty <- matrix("numeric",nrow=10, ncol=10)
for (j in c(1:10)){
  for (i in c(1:10)){
    accrued_interest = bond.TCF(settle=clean_price_date[j],mature=maturity_date[i],coupon=coupon[i])$accrued
    dirty[j,i]= accrued_interest + clean_price_matrix[j,i]
  }
}

## spot_rate:

## only the first five bonds hold the term from 1-5 years

matrix_spot <- matrix("numeric", nrow=10, ncol=10)
for (j in 1:10){
  for (i in 1:10){ 
    dirty_price = as.numeric(dirty[j,i])
    coupon_value = as.numeric(df$Coupon[i]*100/2)
    face = 100
    year_to_maturity = as.numeric(df$Years_to_Maturity[i])
    matrix_spot[i,j] = 2*(((coupon_value+face)/dirty_price)^(1/(2*year_to_maturity))-1)
  }
}

```

